### ISSUE TITLE
Menu Commands

### ISSUE THREAD

**Issue by clarotech** [laggery/vscode-fhir-tools#1]
I have installed the extension and do not see the new commends in the "Edit" menu (as per your screenshots).

I have tried with both an XML and JSON file in the editor but neither work.

**Comment by laggery** [comment]
Hi

Thanks for your message.

Did you try to restart vscode?
Have you the latest version of vscode?

Thanks for your help
Yannick

**Comment by clarotech** [comment]
Yes - I am running the latest build. Restarting VS code has no effect. I do see the commends via the command palette.

**Comment by laggery** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest version.
You can also contribute directly by providing a patch.

Thank you!
