### ISSUE TITLE
FHIR update Java Validator and IGPublisher downloads an empty file

### ISSUE THREAD

**Issue by HerbertPolz** [laggery/vscode-fhir-tools#14]
I installed the FHIR tools today and got the message 
`Error: Invalid or corrupt jarfile`

it turned out that publisher.jar and validator_cli.jar where only 1 KB in size.

Downloading the file directly and just running "FHIR run IGPublisher" now work

**Comment by laggery** [comment]
Hi @HerbertPolz 

Thanks for opening the issue.
I will try to reproduce and fix the Problem in the next few days.

Best regards
Yannick

**Comment by laggery** [comment]
I just published a new version, and I could not reproduce this problem.

Reopen this issue if you still have the problem.
