### ISSUE TITLE
XML<->JSON conversion to new file

### ISSUE THREAD

**Issue by seanmcilvenna** [laggery/vscode-fhir-tools#16]
Can you add functionality to convert between XML and JSON without simply replacing the current file.
For example, I'd like to be able to select a file `someFile.xml`, right-click on it, select "FHIR XML to JSON", and have it create a _new_ `someFile.json`, rather than replacing the .XML file with .JSON file.

**Comment by laggery** [comment]
Hello @seanmcilvenna 

Thanks for your suggestion.

I just published a new version. You have now the choice to convert the resource in a new file.

Let me know if you find some bugs with this feature.

Best regards
Yannick
