### ISSUE TITLE
Using custom jar file

### ISSUE THREAD

**Issue by dmatthews-infoway** [laggery/vscode-fhir-tools#19]
we are using an older version of FHIR  that requires a custom jar file.  I would like to be able to indicate that the custom params are all that is to be used, and that the -jar param must be included in the user defined parameters. vs using the jar the extension retrieved.

I would also like to have the parameters/settings saved so that I don't need to copy and paste the parameters each time I want to validate a file.

**Comment by laggery** [comment]
Hello @dmatthews-infoway 

Thanks for your message.

I would say that it is not an issue with the product, but a feature request. All the code is open source and if you want you can implement this feature and I will publish the new version.

I can offer my services and develop this feature request. If you are interested, I will be happy to send you an offer. Let me know and contact me directly at lagger.yannick@gmail.com

Best regards
Yannick Lagger
