### ISSUE TITLE
Post conversion document type

### ISSUE THREAD

**Issue by clarotech** [laggery/vscode-fhir-tools#2]
Starting with a FHIR JSON file, I ran the JSON to XML conversion

The XML was created correctly, however, the language mode was still JSON - can this be flipped to XML automatically?
![image](https://user-images.githubusercontent.com/20049400/69140778-196da680-0abb-11ea-969b-a1ab8cdf807a.png)

**Comment by laggery** [comment]
Hi @clarotech 

Thanks for your message.

This is strange when I do the conversion the language mode is also changing by me.

Have you the problem also after save the file?
Have you the problem also reopen the file?
Have you the latest version of vscode?

Thanks for your help
Yannick

**Comment by clarotech** [comment]
I am running the latest version of vs code.

The problem is only if I have not saved the file. If the file has been saved then it works ok.

**Comment by laggery** [comment]
Thanks for your reply.

Which OS did you use?
I did my test on Windows 10. Maybe it is not working the same way on other platforms.

**Comment by laggery** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the latest version.
You can also contribute directly by providing a patch.

Thank you!
