### ISSUE TITLE
Does not run when user's path contains spaces

### ISSUE THREAD

**Issue by OdedDvir** [laggery/vscode-fhir-tools#22]
When the user's working dir contains spaces, it failes to run:
![image](https://user-images.githubusercontent.com/57219704/235320503-9108b75d-47e5-45f2-9570-3fc87493f3b6.png)
This can be fixed easily simply by wrapping the validator's path with "".

**Comment by laggery** [comment]
Thanks for opening the issue.

I just published the fix.

Best regards
Yannick
