### ISSUE TITLE
It validates only against FHIR 4.0

### ISSUE THREAD

**Issue by ghost** [laggery/vscode-fhir-tools#3]
When validating a structure definition you can read the fhirVersion element and base the argument for -version on the HL7 validator on this value. fhirVersion is not a mandatory field so the -version can be 4.0 by default. An alternative is to have the version be configurable.

**Comment by laggery** [comment]
Hi Hans

Thanks for your message.

I will add the possibility to set all the options of the jar like the print screen bellow:
![menu](https://user-images.githubusercontent.com/2563295/69168747-8c950e00-0af7-11ea-8b36-9dcb2e086ae6.png)
![input](https://user-images.githubusercontent.com/2563295/69168773-9585df80-0af7-11ea-81a1-47c2931f8c13.png)

I hope to be able to add this feature and publish a new version by the end of the week.

**Comment by ghost** [comment]
Thanks for the reply @laggery .
This would help and give the option to also do snapshot generation :)

**Comment by laggery** [comment]
Hi @HansPhilips 

I just published a new version with the asked feature.

Let me know if I have to change anything
