### ISSUE TITLE
empty collections are not handled correctly

### ISSUE THREAD

**Issue by jvitrifork** [laggery/vscode-fhir-tools#4]
According to http://hl7.org/fhirpath/#null-and-empty missing attrbitutes should be treated as empty collections. This is currently not the case

**Comment by laggery** [comment]
Hi @jvitrifork 

Thanks for your message.

I use the npm package “fhirpath” from October in version “0.17.4”. I will update it to the actual version “1.0.2” and see if this bug will be fixed.

Is it possible to send me a resource, a fhirpath query and the expected result?

This would allow me to fully understand the problem and to solve it adequately.

Thanks for your help
Yannick

**Comment by jvitrifork** [comment]
Hi Yannick -

I'm afraid that I've forgotten the possible bug that I've thought I found. If it comes to my mind again, I'll get back to you

**Comment by laggery** [comment]
Hi @jvitrifork 

I updated the « fhirpath » library to the latest version and published a new version.
Therefore I'm going to close this issue. If you remember the problem let me know and reopen this issue.

Thanks for your help
Yannick
