### ISSUE TITLE
'FHIR validate resource' command didn’t handle the case of spaces in the file name

### ISSUE THREAD

**Issue by yankunhuang-pku** [laggery/vscode-fhir-tools#9]
If the file name contains any spaces, the validation will failed.

If the file name is 'test data.json', the command will run the CL
`java -jar c:\Users\XXX\.vscode\extensions\yannick-lagger.vscode-fhir-tools-1.4.0\validator_cli.jar test data.json -version 4.0.1`
which will lead to the issue to parse the file name.

I think the command should run the CL with "" like:
`java -jar c:\Users\XXX\.vscode\extensions\yannick-lagger.vscode-fhir-tools-1.4.0\validator_cli.jar "test data.json" -version 4.0.1`

**Comment by laggery** [comment]
Hello @yankunhuang-pku 
 
Thanks for your message.

I will look into correcting the problem and keep you informed.

Best regards
Yannick

**Comment by laggery** [comment]
Hi @yankunhuang-pku

I have just published a new version which corrects the validation with files containing spaces

Let me know if you find any other bugs

Best regards
Yannick
